### ISSUE TITLE
Extension breaks debugging for non Device-Simulator Python Workspaces

### ISSUE THREAD

**Issue by julianrendell** [microsoft/vscode-python-devicesimulator#389]
Using MacOS 11.2.1, Python 3.9.1 (via home-brew), create a simple Python project (I used a virtual env.)

After Pillow hack (see #377 ), extension should be "silently" added (even though this workspace is not intended for use with Device Simulator...)

Try to debug a simple "hello world" python script -> broken debug session. Unable to step, no variables showing in debug pane, etc.

In the developer console:

```
DSE Ignoring pywin32: markers 'platform_system == "Windows"' don't match your environmentIgnoring PyObjC: markers 'platform_system == "darwin"' don't match your environmentRequirement already satisfied: playsound==1.2.2 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from -r ./out/requirements.txt (line 1)) (1.2.2)Collecting applicationinsights==0.11.9  Using cached applicationinsights-0.11.9-py2.py3-none-any.whl (58 kB)Requirement already satisfied: python-socketio==4.3.1 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from -r ./out/requirements.txt (line 3)) (4.3.1)Requirement already satisfied: requests==2.22.0 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from -r ./out/requirements.txt (line 4)) (2.22.0)Requirement already satisfied: uflash==1.3.0 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from -r ./out/requirements.txt (line 7)) (1.3.0)Collecting adafruit-circuitpython-fancyled==1.3.3  Using cached adafruit_circuitpython_fancyled-1.3.3-py3-none-any.whlRequirement already satisfied: Pillow in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from -r ./out/requirements.txt (line 9)) (8.1.0)Collecting adafruit-circuitpython-bitmap_font==1.1.0  Using cached adafruit_circuitpython_bitmap_font-1.1.0-py3-none-any.whlCollecting adafruit-circuitpython-display-shapes==1.2.0  Using cached adafruit_circuitpython_display_shapes-1.2.0-py3-none-any.whlCollecting adafruit-circuitpython-neopixel==5.0.0  Using cached adafruit_circuitpython_neopixel-5.0.0-py3-none-any.whlRequirement already satisfied: Adafruit-Blinka in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from adafruit-circuitpython-bitmap_font==1.1.0->-r ./out/requirements.txt (line 10)) (6.2.2)Requirement already satisfied: python-engineio>=3.9.0 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from python-socketio==4.3.1->-r ./out/requirements.txt (line 3)) (4.0.0)Requirement already satisfied: six>=1.9.0 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from python-socketio==4.3.1->-r ./out/requirements.txt (line 3)) (1.15.0)Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from requests==2.22.0->-r ./out/requirements.txt (line 4)) (3.0.4)Requirement already satisfied: certifi>=2017.4.17 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from requests==2.22.0->-r ./out/requirements.txt (line 4)) (2020.12.5)Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from requests==2.22.0->-r ./out/requirements.txt (line 4)) (1.25.11)Requirement already satisfied: idna<2.9,>=2.5 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from requests==2.22.0->-r ./out/requirements.txt (line 4)) (2.8)Requirement already satisfied: Adafruit-PlatformDetect>=3.1.0 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from Adafruit-Blinka->adafruit-circuitpython-bitmap_font==1.1.0->-r ./out/requirements.txt (line 10)) (3.1.1)Requirement already satisfied: Adafruit-PureIO>=1.1.7 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from Adafruit-Blinka->adafruit-circuitpython-bitmap_font==1.1.0->-r ./out/requirements.txt (line 10)) (1.1.8)Requirement already satisfied: pyftdi>=0.40.0 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from Adafruit-Blinka->adafruit-circuitpython-bitmap_font==1.1.0->-r ./out/requirements.txt (line 10)) (0.52.9)Requirement already satisfied: pyserial>=3.0 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from pyftdi>=0.40.0->Adafruit-Blinka->adafruit-circuitpython-bitmap_font==1.1.0->-r ./out/requirements.txt (line 10)) (3.5)Requirement already satisfied: pyusb>=1.0.0 in /Users/julian/Documents/PersonalProjects/Python/dearpygui-expts/venv/lib/python3.9/site-packages (from pyftdi>=0.40.0->Adafruit-Blinka->adafruit-circuitpython-bitmap_font==1.1.0->-r ./out/requirements.txt (line 10)) (1.1.1)Installing collected packages: applicationinsights, adafruit-circuitpython-neopixel, adafruit-circuitpython-fancyled, adafruit-circuitpython-display-shapes, adafruit-circuitpython-bitmap-fontSuccessfully installed adafruit-circuitpython-bitmap-font-1.1.0 adafruit-circuitpython-display-shapes-1.2.0 adafruit-circuitpython-fancyled-1.3.3 adafruit-circuitpython-neopixel-5.0.0 applicationinsights-0.11.9
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618   ERR Cannot read property 'postMessage' of undefined: TypeError: Cannot read property 'postMessage' of undefined
    at MessagingService.sendStartMessage (/Users/julian/.vscode/extensions/ms-python.devicesimulatorexpress-2020.0.36321/out/service/messagingService.js:22:35)
    at DebugAdapter.onExit (/Users/julian/.vscode/extensions/ms-python.devicesimulatorexpress-2020.0.36321/out/debugger/debugAdapter.js:38:31)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:1405
    at Array.forEach (<anonymous>)
    at t.onExit (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:1383)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:27936
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at ChildProcess.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:77:1986)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618   ERR Cannot read property 'postMessage' of undefined: TypeError: Cannot read property 'postMessage' of undefined
    at MessagingService.sendStartMessage (/Users/julian/.vscode/extensions/ms-python.devicesimulatorexpress-2020.0.36321/out/service/messagingService.js:22:35)
    at DebugAdapter.onError (/Users/julian/.vscode/extensions/ms-python.devicesimulatorexpress-2020.0.36321/out/debugger/debugAdapter.js:34:31)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:1338
    at Array.forEach (<anonymous>)
    at t.onError (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:1315)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:27828
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:77:2052)
    at Socket.emit (events.js:327:22)
    at Pipe.<anonymous> (net.js:674:12)
2/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:618   ERR Cannot read property 'postMessage' of undefined: TypeError: Cannot read property 'postMessage' of undefined
    at MessagingService.sendPauseMessage (/Users/julian/.vscode/extensions/ms-python.devicesimulatorexpress-2020.0.36321/out/service/messagingService.js:27:35)
    at DebugAdapter.onWillReceiveMessage (/Users/julian/.vscode/extensions/ms-python.devicesimulatorexpress-2020.0.36321/out/debugger/debugAdapter.js:21:43)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:1069
    at Array.forEach (<anonymous>)
    at t.onWillReceiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:91:1033)
    at g.$sendDAMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:28239)
    at p._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:10276)
    at p._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:9968)
    at p._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:8638)
    at p._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:7440)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:89:5568
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:15515)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:29104
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at d.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:15515)
    at t._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:20765)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:17659
    at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:55:1836)
    at u.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:12880)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:63:12228
    at Socket.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:104:12375)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:186:23)
```

Disabling device simulator restores python debugging.

Note: I've installed device simulator to look at for use with students sometime in the future. I'm not sure if a clean/device simulator workspace is working correctly.

**Comment by julianrendell** [comment]
Just created a clean workspace, and opened a simulator via the command palette. Basic code works (though prospector/pylint is arguing things are undefined, even though intellisense is pulling up the right documentation. I obviously have some more set up to learn!)
